version: '3.8'
services:
  postgres:
    image: postgres
    container_name: pgsql-dev
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
